jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Init Docker swarm
          command: |
            docker swarm init
            docker run -d \
              -p 5000:5000 \
              --restart=always \
              --name registry \
              registry:2
            docker-compose build
            docker-compose push
      - run:
          name: Deploy to swarm
          command: |
            docker stack deploy --compose-file docker-compose.yaml demo
            docker service update demo_lb --publish-add 8443:443
            sleep 30
      - run:
          name: Store logs
          command: |
            mkdir logs
            docker service logs demo_mysql 2>&1 | tee ./logs/demo_mysql.log
            docker service logs demo_consul 2>&1 | tee ./logs/demo_consul.log
            docker service logs demo_consul-template 2>&1 | tee ./logs/demo_consul-template.log
            docker service logs demo_wordpress 2>&1 | tee ./logs/demo_wordpress.log
            docker service logs demo_lb 2>&1 | tee ./logs/demo_lb.log
            docker service logs demo_registrator 2>&1 | tee ./logs/demo_registrator.log
      - store_artifacts:
          path: ./logs/
workflows:
  version: 2
  build:
    jobs:
      - build
